Repository redhat-developer/rsp-client, pull requests merged in 2019-01, with the labels that each got.

#47 Issue #46: Allow required and optional parameters to be specified whi…
  src/client.ts
  src/util/serverModel.ts
  test/client-test.ts
  test/serverModel-test.ts
Labels: in progress, review

#52 Compile tests during build
  .npmignore
  package-lock.json
  package.json
  src/client.ts
  test/client-test.ts
  tsconfig.json
Labels: in progress, review

#51 Update rsp-client to use 0.11.0.Final protocol
  package-lock.json
  src/client.ts
  src/protocol/messages.ts
  src/protocol/protocol.ts
  src/protocol/serverState.ts
  src/util/capabilities.ts
  src/util/serverLauncher.ts
  src/util/serverModel.ts
  test/client-test.ts
  test/serverLauncher-test.ts
Labels: in progress, review, task

#54 Use rimraf cli to delete lib folder
  package.json
Labels: in progress, review

#55 allow using coverage-gutters for vscode
  package.json
  rsp-client.code-workspace
Labels: review

#56 Fix tslint violations
  src/client.ts
  src/util/serverModel.ts
Labels: in progress, review

#57 Add documentation for getServerState method
  src/client.ts
Labels: in progress, review
